### ISSUE TITLE
Disable the sidebar when the configuration is locked

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/aware-client#4]
As discussed, we can disable the left sidebar when the configuration is locked.

Here is the logic used to decide if the study should be locked:
- https://github.com/denzilferreira/aware-client/blob/d78bc4eaccd2c1815e96b952d53981221925507e/aware-phone/src/main/java/com/aware/phone/ui/Aware_Activity.java#L288
- Basically, `if (Aware.getSetting(getApplicationContext(), "study_id").length() > 0)`

This logic can be applied to disable the left sidebar and anything else that may need to be hidden.

**Comment by denzilferreira** [comment]
Yes, this makes sense. I'll do this.

**Comment by denzilferreira** [comment]
Fixed in latest.
