### ISSUE TITLE
Add a manual upload button

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/aware-client#6]
It may already exist when you are part of a study, but it should always be available.

**Comment by denzilferreira** [comment]
It exists if you are part of a study. Where would the data go if you are not part of a study? I see no reason for it to be always visible.

**Comment by rkdarst** [comment]
AWARE has a nice feature that study is different from webservice

If `study_id.length() > 0`, then
- you can't change the settings
- there is a manual upload button

If `status_webservice`:
- upload data to the server

This is extremely good for us, because our data model is that data is linked to users, not studies.  By default, users can adjust and play with their own settings.  I've worked with the system so that it perfectly serves our use case.  Data is _always_ uploaded, it's processed on the server and linked to groups there using a flexible data model.  If someone shouldn't be allowed to adjust things, then set `study_id` to anything.

So, I propose that the manual upload button is controlled by `status_webservice`, not `study_id`.  Thanks for pointing this out!  It's a nice and simple fix.

**Comment by denzilferreira** [comment]
Fixed in latest push.
Denzil;

**Comment by rkdarst** [comment]
Fixed in latest for a while now.

**Comment by rkdarst** [comment]
@denzilferreira, by the way, I just noticed that the UI element is not updated (for change of `status_webservice` value) until the app is closed and reopened.  Similar to the thing denzilferreira/aware-client#28.  Latest version.

**Comment by denzilferreira** [comment]
Hum, I'll check. I've been fixing other pending issues but I'll add this to my to-do.

Denzil; On Sun, Aug 28, 2016 at 3:55 PM, Richard Darst < notifications@github.com [notifications@github.com] > wrote:
@denzilferreira [https://github.com/denzilferreira] , by the way, I just noticed that the UI element is not updated (for change of status_webservice value) until the app is closed and reopened. Similar to the thing denzilferreira/aware-client#28 [https://github.com/denzilferreira/aware-client/issues/28] . Latest version.

**Comment by rkdarst** [comment]
Yeah, I wouldn't say it's a too important or urgent issue, but thought it's best to mention it somewhere.
